"""add site_settings table

Revision ID: 365960ea419b
Revises: ae9a52181fbe
Create Date: 2026-03-25 03:11:42.535916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365960ea419b'
down_revision: Union[str, None] = 'ae9a52181fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_theme', sa.String(length=20), nullable=False),
    sa.Column('last_theme_changed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
